/**
 * utils/workflowMatrix.js
 * The Law Book of allowed transitions and role permissions.
 */
const { STATUS, ROLE } = require('./constants');

const WORKFLOW_MATRIX = {
    [STATUS.PENDING]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.REJECTED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.IN_PROGRESS]: {
        [STATUS.RESOLVED]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.ESCALATED]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.ON_HOLD]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.PENDING]: [ROLE.ADMIN] // Manual reset by admin
    },
    [STATUS.ESCALATED]: {
        [STATUS.RESOLVED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.IN_PROGRESS]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.RESOLVED]: {
        [STATUS.REOPENED]: [ROLE.STUDENT, ROLE.ADMIN, ROLE.PRINCIPAL]
    },
    [STATUS.REJECTED]: {
        [STATUS.REOPENED]: [ROLE.STUDENT, ROLE.ADMIN] // Student can appeal/reopen their case
    },
    [STATUS.REOPENED]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.REJECTED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.ON_HOLD]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    }
};

module.exports = {
    WORKFLOW_MATRIX
};
