/**
 * utils/workflowMatrix.js
 * The Law Book of allowed transitions and role permissions.
 */
const { STATUS, ROLE } = require('./constants');

const WORKFLOW_MATRIX = {
    [STATUS.PENDING]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.REJECTED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.IN_PROGRESS]: {
        [STATUS.RESOLVED]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.ESCALATED]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.ON_HOLD]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.PENDING]: [ROLE.ADMIN] // Manual reset by admin
    },
    [STATUS.ESCALATED]: {
        [STATUS.RESOLVED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.IN_PROGRESS]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.RESOLVED]: {
        [STATUS.REOPENED]: [ROLE.STUDENT, ROLE.ADMIN, ROLE.PRINCIPAL]
    },
    [STATUS.REJECTED]: {
        [STATUS.REOPENED]: [ROLE.STUDENT, ROLE.ADMIN] // Student can appeal/reopen their case
    },
    [STATUS.REOPENED]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN],
        [STATUS.REJECTED]: [ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    },
    [STATUS.ON_HOLD]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF, ROLE.HOD, ROLE.PRINCIPAL, ROLE.ADMIN]
    }
};

const WORKFLOW_V2 = {
    [STATUS.SUBMITTED]: {
        [STATUS.FORWARDED]: [ROLE.ADMIN],
        [STATUS.REJECTED_BY_ADMIN]: [ROLE.ADMIN]
    },
    [STATUS.FORWARDED]: {
        [STATUS.HOD_VERIFIED]: [ROLE.HOD],
        [STATUS.RETURNED_TO_ADMIN]: [ROLE.HOD]
    },
    [STATUS.HOD_VERIFIED]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF]
    },
    [STATUS.IN_PROGRESS]: {
        [STATUS.STAFF_RESOLVED]: [ROLE.STAFF]
    },
    [STATUS.STAFF_RESOLVED]: {
        [STATUS.HOD_APPROVED]: [ROLE.HOD],
        [STATUS.HOD_REWORK_REQUIRED]: [ROLE.HOD]
    },
    [STATUS.HOD_REWORK_REQUIRED]: {
        [STATUS.IN_PROGRESS]: [ROLE.STAFF]
    },
    [STATUS.HOD_APPROVED]: {
        [STATUS.CLOSED]: [ROLE.STUDENT],
        [STATUS.REOPENED]: [ROLE.STUDENT]
    },
    [STATUS.REOPENED]: {
        [STATUS.HOD_VERIFIED]: [ROLE.HOD] // HOD re-assesses and re-assigns
    }

};

module.exports = {
    WORKFLOW_MATRIX,
    WORKFLOW_V2
};

